name: siginsignup
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  google_fonts:
  firebase_auth:

  flutter_downloader: ^1.5.0
  dio: any
  path_provider: ^1.6.14
  permission_handler: ^5.0.1+1
  ext_storage: any
  shared_preferences: ^0.5.6+3
  font_awesome_flutter: ^8.11.0
  # firebase_storage: 3.0.4
  # image_picker: ^0.6.7+4
  # image_cropper: 1.0.2
  razorpay_flutter: ^1.2.5
  video_player_web: ^0.1.0
  flutter_rating_bar: ^4.0.0
  google_sign_in:
  firebase_core:
  image_picker: ^0.6.7+17
  pdf_flutter: ^1.1.3
  file_picker: ^1.13.3
  pdf: ^1.13.0
  toast: ^0.1.5
  video_player: ^0.5.1
  youtube_player_flutter: ^7.0.0+7
  progress_button: ^0.0.2
  cloud_firestore:
  firebase_storage: ^3.1.6
  fluttertoast: ^7.1.8
  email_validator: "^1.0.5"
  flutter_overboard: ^1.1.5
  # provider: ^3.1.0
  flutter_custom_clippers: ^1.1.2

  easy_gradient_text: ^1.0.0
  concentric_transition: ^0.1.1
  flutter_spinkit: "^4.1.2"
  flutter_easyloading: ^2.2.2
  multiple_stream_builder: ^1.1.0
  awesome_dialog: ^1.3.2
  animated_button: ^0.1.3
  agora_rtc_engine: ^3.3.2

dev_dependencies:
  flutter_launcher_icons: "^0.8.0"
  flutter_test:
    sdk: flutter
flutter_icons:
  android: "launcher_icon"

  image_path: "assets/tutor.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/googleicon.png
    - assets/upload.png
    - assets/student.png
    - assets/teacher.png
    - assets/tutor.png
    - assets/kids.jpg
    - assets/history.jpg
    - assets/lifestyle.jpg
    - assets/amer.png
    - assets/murad.jpeg
    - assets/edress.jpeg
    - assets/beginner.jpg
    - assets/advanced.jpg
    - assets/inter.jpg
    - assets/donate.png
    - assets/devs.jpg 
    - assets/checklists.png
    - assets/powered_by.png
    - assets/quran.png
    - assets/grammar.png
    - assets/sarf.png
    - assets/speaking.png
    - assets/writer.png
    - assets/login.png
    - assets/signup.png
    - assets/teachersign.png
    - assets/information.png
    - assets/classroom.png
    - assets/customer-service.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/Montserrat-Regular.ttf
        - asset: assets/Montserrat-Bold.ttf
          weight: 700
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
